//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Services.Base {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Services.Base.ServiceResources", typeof(ServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0.66 ähnelt.
        /// </summary>
        internal static string BrightnessThreshold {
            get {
                return ResourceManager.GetString("BrightnessThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (?&lt;name&gt;\[[\w\s]+\]){0,1}(?&lt;email&gt;[\w-\.]+\@[\w-\.]+\.[\w]{2,4}) ähnelt.
        /// </summary>
        internal static string ContentRenderService_EmailLinkRegex {
            get {
                return ResourceManager.GetString("ContentRenderService_EmailLinkRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (?&lt;name&gt;\[[\w\s]+\]){0,1}\s?(?&lt;number&gt;(?:\+|0{1,2})(?:[-\/\s]?\d+)+) ähnelt.
        /// </summary>
        internal static string ContentRenderService_TelLinkRegex {
            get {
                return ResourceManager.GetString("ContentRenderService_TelLinkRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (?&lt;name&gt;\[.+?\])?(?&lt;link&gt;(?:http[s]:\/\/|www).+?)(?:\s|$) ähnelt.
        /// </summary>
        internal static string ContentRenderService_WebLinkRegex {
            get {
                return ResourceManager.GetString("ContentRenderService_WebLinkRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 255, 164, 164, 164 ähnelt.
        /// </summary>
        internal static string DarkBackgroundTextColor {
            get {
                return ResourceManager.GetString("DarkBackgroundTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 255, 88, 88, 88 ähnelt.
        /// </summary>
        internal static string DarkTextColor {
            get {
                return ResourceManager.GetString("DarkTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vwxf xblj qllm kifv ähnelt.
        /// </summary>
        internal static string Email_Password {
            get {
                return ResourceManager.GetString("Email_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die spitefr@gmail.com ähnelt.
        /// </summary>
        internal static string Email_Sender {
            get {
                return ResourceManager.GetString("Email_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 255, 255, 255, 255 ähnelt.
        /// </summary>
        internal static string LightTextColor {
            get {
                return ResourceManager.GetString("LightTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4000 ähnelt.
        /// </summary>
        internal static string Toast_DefaultDisplayTime {
            get {
                return ResourceManager.GetString("Toast_DefaultDisplayTime", resourceCulture);
            }
        }
    }
}
